name: dart_bloom_filter
description: A Dart implementation of a bloom filter. Bloom filters are a space-efficient probabilistic data structure that is used to test whether an element is a member of a set.
version: 1.0.0
repository: https://github.com/sigmapie8/dart_bloom_filter

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  bit_array: ^2.3.0
  json_annotation: ^4.9.0
  murmurhash: ^1.0.1

dev_dependencies:
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3
