name: dart_bloom_filter
description: A Dart implementation of a bloom filter. Bloom filters are a space-efficient probabilistic data structure that is used to test whether an element is a member of a set.
version: 1.0.0
repository: https://github.com/sigmapie8/dart_bloom_filter

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  murmurhash: ^1.0.1
  bit_array: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3